# Generated by Django 2.2.5 on 2019-10-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('num_cuenta', models.BigIntegerField()),
                ('correo', models.EmailField(max_length=255)),
                ('product', models.IntegerField(choices=[(1, 'Dapac Cerdas'), (2, 'Aviplus'), (3, 'Camperbroiler Granulado'), (4, 'Conchilla'), (5, 'Dapac Vacas'), (6, 'Nantacor'), (7, 'Guidolin Nutri Potros'), (8, 'Red Kite')], default=1)),
                ('pay', models.IntegerField(choices=[(1, 'Tarjeta'), (2, 'Paypal')], default=1)),
            ],
        ),
    ]
