# Generated by Django 2.2.7 on 2019-11-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0002_auto_20191110_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_food',
            name='pay',
            field=models.CharField(choices=[('Tarjeta', 'j'), ('Paypal', 'k')], default='Tarjeta', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment_food',
            name='product',
            field=models.CharField(choices=[('Dapac Cerdas', 'a'), ('Aviplus', 'b'), ('Camperbroiler Granulado', 'c'), ('Conchilla', 'd'), ('Dapac Vacas', 'f'), ('Nantacor', 'g'), ('Guidolin Nutri Potros', 'h'), ('Red Kite', 'i')], default='Dapac Cerdas', max_length=255),
        ),
    ]
