# Generated by Django 2.2.7 on 2019-11-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0003_auto_20191110_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_food',
            name='pay',
            field=models.CharField(choices=[('Tarjeta', 1), ('Paypal', 2)], default='Tarjeta', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment_food',
            name='product',
            field=models.CharField(choices=[('Dapac Cerdas', 1), ('Aviplus', 2), ('Camperbroiler Granulado', 3), ('Conchilla', 4), ('Dapac Vacas', 5), ('Nantacor', 6), ('Guidolin Nutri Potros', 7), ('Red Kite', 8)], default='Dapac Cerdas', max_length=255),
        ),
    ]
